--최종결과 : AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES*PRICE AS SALES
--필요한 테이블 : 3개 다
--조건 : 2022년 1월의 도서 판매 데이터를 기준
--그룹 : AUTHOR_ID, AUTHOR_NAME, GATEGORY
--소팅 : AUTHOR_ID, CATEGORY DESC;
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS SALES
FROM ((BOOK B INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) 
        INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID)
WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;