-- 코드를 입력하세요
--최종결과 : 년, 월, 성별, 상품을 구매한 회원수
--필요한 테이블 : USER_INFO JOIN ONLINE_SALE 
--조건 : WHERE 성별 IS NOT NULL
--그룹 : 년, 월, 성별 별
--그룹 조건 :
--소팅 : 년, 월, 성별 별 ASC
SELECT TO_CHAR(S.SALES_DATE,'YYYY') as YEAR, 
TO_NUMBER(TO_CHAR(S.SALES_DATE,'MM')) as MONTH, 
U.GENDER,
COUNT(DISTINCT(U.USER_ID)) as USERS
FROM USER_INFO U JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE,'YYYY'), TO_CHAR(S.SALES_DATE,'MM') , U.GENDER
ORDER BY YEAR,MONTH, U.GENDER;