-- 코드를 입력하세요
--최종결과 : RPO.PRODUCT_ID, PRO.PRODUCT_NAME, PRO.PRICE*ORD.AMOUNT as TOTAL_SALES
--필요한 테이블 : FOOD_ORDER ORD JOIN FOOD_PRODUCT PRO ON ORD.PRODUCT_ID = PRO.PRODUCT_ID
--조건 :  2022년 5월인 식품
--그룹 : 
--그룹 조건 :
--소팅 :ORDER BY TOTAL_SALES DESC,PRODUCT_ID;
SELECT PRO.PRODUCT_ID, 
PRO.PRODUCT_NAME, 
SUM(PRO.PRICE * ORD.AMOUNT) as TOTAL_SALES
FROM FOOD_ORDER ORD INNER JOIN FOOD_PRODUCT PRO ON ORD.PRODUCT_ID = PRO.PRODUCT_ID
WHERE TO_CHAR(ORD.PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY PRO.PRODUCT_ID, PRO.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID;
