SELECT FLAVOR
FROM (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER + FH.TOTAL_ORDER) as TOTAL
    FROM JULY J JOIN FIRST_HALF FH ON J.FLAVOR = FH.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY TOTAL DESC)
WHERE ROWNUM <=3;