-- 코드를 입력하세요
--최종결과 : USER_ID, NICKNAME, 총거래금액
--필요한 테이블 : USED_GOODS_USER U JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
--조건 : 총금액 70만원 이상
--소팅 : 총거래금액 오름차순 
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_USER U INNER JOIN USED_GOODS_BOARD B ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE);