-- 코드를 입력하세요
--최종결과 : INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
--필요한 테이블 : ICECREAM_INFO JOIN FIRST_HALF 
--조건 : x
--그룹 : INGREDIENT_TYPE
--그룹(집계)조건 : x
--소팅 :  SUM(TOTAL_ORDER) asc;
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM ICECREAM_INFO NATURAL JOIN FIRST_HALF 
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;