-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, C.REPLY_ID, C.WRITER_ID, C.CONTENTS, TO_CHAR(C.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY C ON A.BOARD_ID = C.BOARD_ID
WHERE TO_CHAR(A.CREATED_DATE,'YYYY-MM-DD') LIKE '2022-10-__'
ORDER BY C.CREATED_DATE, A.TITLE;
            